#   /*
#    * Copyright (c) 2022-2025 KCloud-Platform-IoT Author or Authors. All Rights Reserved.
#    *
#    * Licensed under the Apache License, Version 2.0 (the "License");
#    * you may not use this file except in compliance with the License.
#    * You may obtain a copy of the License at
#    *
#    *   http://www.apache.org/licenses/LICENSE-2.0
#    *
#    * Unless required by applicable law or agreed to in writing, software
#    * distributed under the License is distributed on an "AS IS" BASIS,
#    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    * See the License for the specific language governing permissions and
#    * limitations under the License.
#    *
#    */
jasypt:
  encryptor:
    password: @JASYPT-ENCRYPTOR-PASSWORD@

server:
  ssl:
    # 开启证书
    enabled: @SSL-ENABLED@
    # 证书位置
    key-store: classpath:scg-keystore.p12
    # 证书别名
    key-alias: ${spring.application.name}
    # 秘钥类型
    key-store-type: PKCS12
    # 证书密码
    key-store-password: laokou
  http2:
    enabled: @SSL-ENABLED@
  forward-headers-strategy: framework
  shutdown: graceful
  port: ${SERVER_PORT:1111}
  servlet:
    encoding:
      charset: UTF-8
  undertow:
    threads:
      # 设置IO线程数，来执行非阻塞任务，负责多个连接数
      io: 16
      # 工作线程数
      worker: 512
    # 每块buffer的空间大小
    buffer-size: 2048
    # 分配堆外内存
    direct-buffers: true
spring:
  application:
    name: ${SERVICE_ID:laokou-auth}
  profiles:
    active: @PROFILE-ACTIVE@
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 2m
  session:
    redis:
      repository-type: indexed
      namespace: spring:session:auth
    timeout: 3600
  # mail
  mail:
    host: smtp.163.com
    username: koushenhai@163.com
    password: ENC(lyyF4qBHGnbwEHfz/RSj2JtahbLqWjMrkFz0hGqcND3Hp19Ea6aJejxqNBYCCGnL7iw8n11Y1xvM7Hp9EDPgtg==)
    default-encoding: UTF-8
  # security
  security:
    oauth2:
      authorization-server:
        enabled: true
        # 多租户
        multiple-issuers-allowed: false
        client:
          default:
            token:
              authorization-code-time-to-live: 5m
              access-token-time-to-live: 5m
              refresh-token-time-to-live: 1h
              device-code-time-to-live: 5m
            registration:
              id: 95TxSsTPFA3tF12TBSMmUVK0da
              client-id: 95TxSsTPFA3tF12TBSMmUVK0da
              client-name: OAuth2.1认证
              client-secret: "{bcrypt}$2a$10$BDcxgmL3WYk7G.QEDTqlBeSudNlV3KUU/V6iC.hKlAbGAC.jbX2fO"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - test
                - username_password
                - mail
                - mobile
                - client_credentials
                - refresh_token
                - authorization_code
                - urn:ietf:params:oauth:grant-type:device_code
                - urn:ietf:params:oauth:grant-type:jwt-bearer
                - urn:ietf:params:oauth:grant-type:token-exchange
              scopes:
                - read
                - write
              redirect-uris:
                - http://127.0.0.1:8000
                - http://127.0.0.1:8001
                - https://laokou.org.cn
              post-logout-redirect-uris:
                - http://127.0.0.1:8000
                - http://127.0.0.1:8001
                - https://laokou.org.cn
            # 客户端请求访问时需要授权同意
            require-authorization-consent: true
            # PKCE
            require-proof-key: false
      resource-server:
        enabled: true
        request-matcher:
          ignore-patterns:
            GET:
              - /v3/api-docs/**=laokou-auth
              - /swagger-ui.html=laokou-auth
              - /swagger-ui/**=laokou-auth
              - /actuator/**=laokou-auth
              - /error=laokou-auth
              - /v3/captchas/{uuid}=laokou-auth
              - /v3/secrets=laokou-auth
              - /graceful-shutdown=laokou-auth
              - /doc.html=laokou-auth
              - /webjars/**=laokou-auth
            POST:
              - /v3/captchas/send/mail=laokou-auth
              - /v3/captchas/send/mobile=laokou-auth
            DELETE:
              - /v3/tokens=laokou-auth
  datasource:
    dynamic:
      # 默认false,建议线上关闭
      p6spy: false
      #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源
      strict: true
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: @DATASOURCE-DRIVER-CLASS-NAME@
          url: jdbc:@DATASOURCE-PLATFORM@://@DATASOURCE-HOST@:@DATASOURCE-PORT@/kcloud_platform?tcpKeepAlive=true&reWriteBatchedInserts=true&stringtype=unspecified&ApplicationName=laokou-auth&useSSL=false
          username: ENC(l126CTjtLG8OkXRNs5aofcN96EQpbQmQorTqpnWFMvcysQLjNBEuX+9f6hLwdoEk)
          password: ENC(BhsqlMbKjWVxPseo9OX8osLuL2Y4rWfGTyBRXaZTsAdzZ1Z4rBewBmoXjf2Hnu4o)
          # https://blog.csdn.net/u014644574/article/details/123680515
          hikari:
            connection-timeout: 180000
            validation-timeout: 3000
            idle-timeout: 180000
            max-lifetime: 1800000
            maximum-pool-size: 60
            minimum-idle: 10
            is-read-only: false
        domain:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: @DATASOURCE-DRIVER-CLASS-NAME@
          url: jdbc:@DATASOURCE-PLATFORM@://@DATASOURCE-HOST@:@DATASOURCE-PORT@/kcloud_platform_domain?tcpKeepAlive=true&reWriteBatchedInserts=true&stringtype=unspecified&ApplicationName=laokou-auth&useSSL=false
          username: ENC(l126CTjtLG8OkXRNs5aofcN96EQpbQmQorTqpnWFMvcysQLjNBEuX+9f6hLwdoEk)
          password: ENC(BhsqlMbKjWVxPseo9OX8osLuL2Y4rWfGTyBRXaZTsAdzZ1Z4rBewBmoXjf2Hnu4o)
          # https://blog.csdn.net/u014644574/article/details/123680515
          hikari:
            connection-timeout: 180000
            validation-timeout: 3000
            idle-timeout: 180000
            max-lifetime: 1800000
            maximum-pool-size: 60
            minimum-idle: 10
            is-read-only: false
  data:
    redis:
      client-type: lettuce
      host: redis
      port: 6379
      password: ENC(BhsqlMbKjWVxPseo9OX8osLuL2Y4rWfGTyBRXaZTsAdzZ1Z4rBewBmoXjf2Hnu4o)
      connect-timeout: 60000ms #连接超时时长（毫秒）
      timeout: 60000ms #超时时长（毫秒）
      lettuce:
        pool:
          max-active: -1 #连接池最大连接数（使用负值表示无极限）
          max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 500 #连接池最大空闲连接
          min-idle: 200 #连接池最小空间连接

  cloud:
    # sentinel
    sentinel:
      datasource:
        # 自定义名称
        db0:
          nacos:
            server-addr: @NACOS-CONFIG-ADDRESS@
            namespace: @NACOS-NAMESPACE@
            data-id: auth-flow.json
            data-type: json
            group-id: @NACOS-GROUP@
            username: @NACOS-USERNAME@
            password: @NACOS-PASSWORD@
            rule-type: flow
      web-context-unify: false
      eager: true #开启饥饿加载，直接初始化
      transport:
        dashboard: sentinel:8972
      filter:
        enabled: true
    # loadbalancer
    loadbalancer:
      nacos:
        enabled: true
    # network
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*
# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    propagation:
      type: w3c
    # 采样率 => 100%
    sampling:
      probability: 1
  otlp:
    tracing:
      endpoint: http://otel-collector:4317/v1/traces
      compression: gzip
      timeout: 10s
      transport: grpc
    metrics:
      export:
        enabled: false
  metrics:
    tags:
      application: ${spring.application.name}

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

sms:
  type: gyy
  gyy:
    template-id: ENC(h+6CtZDd1st7pAOcFNcjNDmglNIkRsEMFAwPv76STLe7kxdTX0lyX+ZJ4tO9zY3Bd7Xp5511saK9E7nr0ZlnwvPypbTBqz6U/ICCu03EEo4=)
    sign-id: ENC(6DZexca4yMNi/4FiyS0Vwa9uSRUidUpCo9N390puXIZBAGC/T3PxSqF01Bv62TzRbY6/O2IsAKISDqfEtDooofRglNcmN9dVx55pZEwV4ck=)
    appcode: ENC(QIuOx6iFUg1VuPvrdarC3Q4kWhIMsnRjPSkAN+cPoRHitIJ58xicWbaT2sAuVo+PW+SBdJfsp0yUpBZX2usHzxOVosw9WYBuBsQYtns2/9c=)

logging:
  config: classpath:log4j2-@PROFILE-ACTIVE@.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.laokou.auth.web

# mybatis-plus
mybatis-plus:
  # 全局处理
  global-config:
    db-config:
      column-format: "\"%s\""
  tenant:
    enabled: true
    ignore-tables:
      - boot_sys_source
      - boot_sys_tenant
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

rocketmq:
  producer:
    group: laokou_producer_group
  name-server: rocketmq-namesrv:9876
  consumer:
    pull-batch-size: 32
