spring:
  application:
    name: laokou-test-elasticsearch
  profiles:
    active: @PROFILE-ACTIVE@
  elasticsearch:
    uris:
      - https://elasticsearch:9200
    username: ENC(288BcA+5uF75oMpMHekXLLG+DBnzJbj3eFEY5uEG9G1TWvv7dR2TXJ8jc13MtHDk)
    password: ENC(BhsqlMbKjWVxPseo9OX8osLuL2Y4rWfGTyBRXaZTsAdzZ1Z4rBewBmoXjf2Hnu4o)
    connection-timeout: 30s
    socket-timeout: 30s
server:
  port: 8082

jasypt:
  encryptor:
    password: @JASYPT-ENCRYPTOR-PASSWORD@

logging:
  config: classpath:log4j2-@PROFILE-ACTIVE@.xml
